'use client';

import React, { useState, useEffect } from 'react';

export interface EscalationItem {
  id: number;
  reference_id: str;
  user_id: string;
  caller_name: string;
  caller_phone: string;
  preferred_contact_method: string;
  language: string;
  issue_category: string;
  urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'EMERGENCY';
  summary: string;
  checked_by_agent: string;
  status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED';
  created_at: string;
  resolved_at?: string;
}

export function EscalationsDashboard() {
  const [escalations, setEscalations] = useState<EscalationItem[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [urgencyFilter, setUrgencyFilter] = useState<string>('ALL');
  const [resolvingId, setResolvingId] = useState<string | null>(null);

  const fetchEscalations = async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/escalations?status=${statusFilter}&urgency=${urgencyFilter}`);
      if (res.ok) {
        const json = await res.json();
        setEscalations(json.data || []);
      }
    } catch (e) {
      console.error('Failed to load escalations:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEscalations();
  }, [statusFilter, urgencyFilter]);

  const handleMarkResolved = async (refId: string) => {
    setResolvingId(refId);
    try {
      const res = await fetch('/api/escalations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reference_id: refId, status: 'RESOLVED' }),
      });
      if (res.ok) {
        fetchEscalations();
      }
    } catch (e) {
      console.error('Failed to resolve escalation:', e);
    } finally {
      setResolvingId(null);
    }
  };

  const getUrgencyBadge = (urgency: string) => {
    switch (urgency) {
      case 'EMERGENCY':
      case 'HIGH':
        return 'bg-red-500/20 text-red-400 border-red-500/30';
      case 'MEDIUM':
        return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'LOW':
      default:
        return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'RESOLVED':
        return 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30';
      case 'IN_PROGRESS':
        return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      case 'OPEN':
      default:
        return 'bg-rose-500/20 text-rose-400 border-rose-500/30';
    }
  };

  const totalCount = escalations.length;
  const openCount = escalations.filter((e) => e.status === 'OPEN').length;
  const highCount = escalations.filter((e) => e.urgency === 'HIGH' || e.urgency === 'EMERGENCY').length;
  const resolvedCount = escalations.filter((e) => e.status === 'RESOLVED').length;

  return (
    <div className="w-full max-w-6xl mx-auto p-4 sm:p-6 space-y-6 text-foreground">
      {/* Top Header & Metrics */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-border pb-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-emerald-400 flex items-center gap-2">
            <span>🚨</span> Human Help Escalation Dashboard
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Real-time human support requests generated by KrishiVani AI Agent
          </p>
        </div>
        <button
          onClick={fetchEscalations}
          className="px-3 py-1.5 rounded-lg bg-emerald-600/20 text-emerald-400 border border-emerald-500/30 hover:bg-emerald-600/30 text-xs font-medium transition-colors"
        >
          🔄 Refresh Feed
        </button>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-card border border-border p-4 rounded-xl">
          <p className="text-xs text-muted-foreground font-medium">Total Requests</p>
          <p className="text-2xl font-bold mt-1 text-white">{totalCount}</p>
        </div>
        <div className="bg-card border border-rose-500/30 p-4 rounded-xl bg-rose-500/5">
          <p className="text-xs text-rose-400 font-medium">Open Tickets</p>
          <p className="text-2xl font-bold mt-1 text-rose-400">{openCount}</p>
        </div>
        <div className="bg-card border border-red-500/30 p-4 rounded-xl bg-red-500/5">
          <p className="text-xs text-red-400 font-medium">High / Emergency</p>
          <p className="text-2xl font-bold mt-1 text-red-400">{highCount}</p>
        </div>
        <div className="bg-card border border-emerald-500/30 p-4 rounded-xl bg-emerald-500/5">
          <p className="text-xs text-emerald-400 font-medium">Resolved</p>
          <p className="text-2xl font-bold mt-1 text-emerald-400">{resolvedCount}</p>
        </div>
      </div>

      {/* Filters Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-muted/40 p-3 rounded-xl border border-border">
        <div className="flex flex-wrap items-center gap-3">
          <label className="text-xs font-semibold text-muted-foreground">Status:</label>
          {['ALL', 'OPEN', 'RESOLVED'].map((st) => (
            <button
              key={st}
              onClick={() => setStatusFilter(st)}
              className={`px-3 py-1 rounded-md text-xs font-medium transition-colors ${
                statusFilter === st
                  ? 'bg-emerald-500 text-black font-bold'
                  : 'bg-background hover:bg-muted text-muted-foreground'
              }`}
            >
              {st}
            </button>
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <label className="text-xs font-semibold text-muted-foreground">Urgency:</label>
          {['ALL', 'HIGH', 'EMERGENCY', 'MEDIUM', 'LOW'].map((urg) => (
            <button
              key={urg}
              onClick={() => setUrgencyFilter(urg)}
              className={`px-3 py-1 rounded-md text-xs font-medium transition-colors ${
                urgencyFilter === urg
                  ? 'bg-emerald-500 text-black font-bold'
                  : 'bg-background hover:bg-muted text-muted-foreground'
              }`}
            >
              {urg}
            </button>
          ))}
        </div>
      </div>

      {/* List of Escalation Cards */}
      {loading ? (
        <div className="py-12 text-center text-sm text-muted-foreground">
          Loading escalations from KrishiVani database...
        </div>
      ) : escalations.length === 0 ? (
        <div className="py-12 text-center border border-dashed border-border rounded-xl bg-muted/20">
          <p className="text-base font-semibold text-muted-foreground">No Escalation Requests Found</p>
          <p className="text-xs text-muted-foreground mt-1">
            KrishiVani creates tickets when farmers report severe crop problems or request human help.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {escalations.map((item) => (
            <div
              key={item.reference_id}
              className="bg-card border border-border rounded-xl p-5 shadow-sm space-y-3 hover:border-emerald-500/50 transition-colors"
            >
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/50 pb-3">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-sm font-bold text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded border border-emerald-500/20">
                    {item.reference_id}
                  </span>
                  <span
                    className={`text-xs px-2.5 py-0.5 rounded-full border font-semibold ${getUrgencyBadge(
                      item.urgency
                    )}`}
                  >
                    {item.urgency} URGENCY
                  </span>
                  <span
                    className={`text-xs px-2.5 py-0.5 rounded-full border font-semibold ${getStatusBadge(
                      item.status
                    )}`}
                  >
                    {item.status}
                  </span>
                </div>

                <span className="text-xs text-muted-foreground font-mono">
                  {new Date(item.created_at).toLocaleString('en-IN', {
                    dateStyle: 'medium',
                    timeStyle: 'short',
                  })}
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
                <div>
                  <p className="text-muted-foreground font-medium">Farmer Details</p>
                  <p className="font-semibold text-sm text-white mt-0.5">{item.caller_name}</p>
                  <p className="text-muted-foreground">
                    Phone: {item.caller_phone} ({item.preferred_contact_method})
                  </p>
                  <p className="text-muted-foreground">Language: {item.language}</p>
                </div>

                <div className="md:col-span-2">
                  <p className="text-muted-foreground font-medium">Issue Summary</p>
                  <p className="text-sm font-normal text-gray-200 mt-0.5 leading-relaxed">
                    {item.summary}
                  </p>
                  {item.checked_by_agent && (
                    <p className="text-xs text-emerald-300/80 mt-1 italic">
                      Agent Checked: {item.checked_by_agent}
                    </p>
                  )}
                </div>
              </div>

              {item.status !== 'RESOLVED' && (
                <div className="flex justify-end pt-2 border-t border-border/30">
                  <button
                    onClick={() => handleMarkResolved(item.reference_id)}
                    disabled={resolvingId === item.reference_id}
                    className="px-4 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow transition-all disabled:opacity-50"
                  >
                    {resolvingId === item.reference_id ? 'Resolving...' : '✓ Mark as Resolved'}
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
