[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "day4-krishivani-memory"
version = "1.0.0"
description = "Day 4 Voice AI agent with SQLite Memory powered by Murf Falcon TTS and LiveKit Agents"
requires-python = ">=3.10, <3.15"

dependencies = [
    "livekit-agents[deepgram,google,silero,turn-detector]~=1.4",
    "livekit-murf>=0.1.1",
    "livekit-plugins-noise-cancellation~=0.2",
    "python-dotenv",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.ruff]
line-length = 88
target-version = "py39"
